version: "3.5"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data
  web:
    build: .
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - 0.0.0.0:3000:3000
    links:
      - mysql
      - redis